[2024-06-06T16:24:50.583+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T16:24:50.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.weather_api_readiness manual__2024-06-06T16:24:38.849173+00:00 [queued]>
[2024-06-06T16:24:50.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.weather_api_readiness manual__2024-06-06T16:24:38.849173+00:00 [queued]>
[2024-06-06T16:24:50.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-06-06T16:24:50.642+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): weather_api_readiness> on 2024-06-06 16:24:38.849173+00:00
[2024-06-06T16:24:50.651+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'weather_api_readiness', 'manual__2024-06-06T16:24:38.849173+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpeluh1_dj']
[2024-06-06T16:24:50.649+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T16:24:50.652+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask weather_api_readiness
[2024-06-06T16:24:50.652+0000] {standard_task_runner.py:63} INFO - Started process 1171 to run task
[2024-06-06T16:24:50.746+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.weather_api_readiness manual__2024-06-06T16:24:38.849173+00:00 [running]> on host 918bc5ab046e
[2024-06-06T16:24:50.942+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='eajavon08@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='weather_api_readiness' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T16:24:38.849173+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T16:24:38.849173+00:00'
[2024-06-06T16:24:50.946+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T16:24:50.947+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-06T16:24:50.949+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Portland&APPID=b3f2e7f8ab423fd0c04f940d301540bc
[2024-06-06T16:24:50.974+0000] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-06T16:24:53.918+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-06T16:24:53.921+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T16:24:53.936+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=weather_api_readiness, run_id=manual__2024-06-06T16:24:38.849173+00:00, execution_date=20240606T162438, start_date=20240606T162450, end_date=20240606T162453
[2024-06-06T16:24:53.968+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T16:24:53.999+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T16:24:54.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
